// Built-in starter template: "Family Holiday — Spain"
// Each item: { text, note }. IDs are assigned at instantiation time (see storage.js instantiateTemplate).
window.MALETA_SEED_TEMPLATE = {
  name: "Family Holiday — Spain",
  sections: [
    {
      title: "To Do Today ☀️",
      items: [
        { text: "Organise someone to feed the cats" },
        { text: "Call over to Emma and ask her to come over", note: "show her the awning + where the cat food is" },
        { text: "Clean and organise the cat litter" },
        { text: "Visit Nanny" },
        { text: "Secure the house", note: "windows, doors, alarm" },
        { text: "Empty bins" },
        { text: "Remove perishables from the fridge" },
        { text: "Charge phones, watches and power banks" },
        { text: "Download boarding passes" },
        { text: "Check in for the flight" },
        { text: "Check the weather forecast" },
        { text: "Set aside passports, wallets and keys", note: "keep out of packed luggage" },
      ],
    },
    {
      title: "Travel Documents 🛂",
      items: [
        { text: "Passport — Joe" },
        { text: "Passport — Éabha" },
        { text: "Boarding passes" },
        { text: "Travel insurance details" },
        { text: "EHIC/GHIC cards" },
        { text: "Driving licence", note: "only if needed" },
        { text: "Wallet and bank cards" },
        { text: "Euros" },
        { text: "House keys" },
      ],
    },
    {
      title: "Electronics 🔌",
      items: [
        { text: "iPhones" },
        { text: "Apple Watches" },
        { text: "AirPods/headphones" },
        { text: "Phone chargers" },
        { text: "Apple Watch chargers" },
        { text: "Power bank" },
        { text: "Kindle/iPad", note: "if bringing" },
      ],
    },
    {
      title: "Clothes — Joe 👕",
      items: [
        { text: "7 T-shirts" },
        { text: "3 pairs of shorts" },
        { text: "Jeans/chinos" },
        { text: "Lightweight trousers" },
        { text: "8–10 pairs of underwear" },
        { text: "8–10 pairs of socks" },
        { text: "2 swim shorts" },
        { text: "Light hoodie/jumper" },
        { text: "Pyjamas" },
        { text: "Trainers" },
        { text: "Flip-flops/sandals" },
        { text: "Cap/hat" },
      ],
    },
    {
      title: "Clothes — Éabha 👗",
      items: [
        { text: "T-shirts/tops" },
        { text: "Shorts" },
        { text: "Dresses", note: "if wanted" },
        { text: "Leggings/light trousers" },
        { text: "Underwear" },
        { text: "Socks" },
        { text: "Pyjamas" },
        { text: "Swimwear" },
        { text: "Light hoodie" },
        { text: "Trainers" },
        { text: "Sandals/flip-flops" },
        { text: "Hat" },
      ],
    },
    {
      title: "Toiletries 🪥",
      items: [
        { text: "Toothbrushes" },
        { text: "Toothpaste" },
        { text: "Deodorant" },
        { text: "Shampoo and conditioner" },
        { text: "Shower gel" },
        { text: "Moisturiser" },
        { text: "Razor" },
        { text: "Hairbrush/comb" },
        { text: "Hair ties", note: "Éabha" },
        { text: "Makeup", note: "if needed" },
        { text: "Lip balm" },
        { text: "Sunscreen SPF 30–50" },
        { text: "After-sun" },
      ],
    },
    {
      title: "Medication 💊",
      items: [
        { text: "Prescription medication" },
        { text: "Paracetamol" },
        { text: "Ibuprofen" },
        { text: "Antihistamines" },
        { text: "Plasters" },
        { text: "Electrolyte sachets" },
      ],
    },
    {
      title: "Beach & Pool 🏖️",
      items: [
        { text: "Beach towels", note: "if not provided" },
        { text: "Beach bag" },
        { text: "Reusable water bottles" },
        { text: "Goggles" },
      ],
    },
    {
      title: "Flight ✈️",
      items: [
        { text: "Snacks" },
        { text: "Empty water bottles", note: "fill after security" },
        { text: "Book/Kindle" },
        { text: "Downloaded films/shows" },
        { text: "Downloaded music/podcasts" },
      ],
    },
    {
      title: "Final House Check 🏠",
      items: [
        { text: "Final passport check" },
        { text: "Lock all windows and doors" },
        { text: "Set the alarm" },
        { text: "Turn off unnecessary electrical items" },
        { text: "Confirm taxi/parking" },
        { text: "Take out the rubbish" },
      ],
    },
  ],
};
